import "./globals.css";
import Footer from "@/components/footer/footer";
import Header from "@/components/main-header/header";
import SideBar from "@/components/sidebar/sideBar";
import { Nunito } from 'next/font/google';

const nunito = Nunito({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "Leonardo",
  description: "Generated by Mekko Digital",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={nunito.className}>
      <body >
        <div className="homePage">
        <SideBar/>
        <div className="main">
        <Header/>
        {children}
        <Footer/>
        </div>
        </div>
      </body>
    </html>
  );
}

